#!/bin/bash
set -ueo pipefail

vnc_version=c68196700ec88c349f919aa03b78766350fd7fff
p9p_version=7b8251125b9f08f03fb9ea26b7617e1551ef6090
vnc_prefix=/usr/local/tigervnc
p9p_prefix=/usr/local/p9p

xorg_url=https://xorg.freedesktop.org/releases/individual/xserver/xorg-server-1.20.9.tar.bz2

vnc_deps=(fltk pam gnutls libjpeg-turbo libxtst pixman
    xorg-xauth xorg-xsetroot xkeyboard-config xorg-xkbcomp
    libgl libgcrypt perl libxdamage libxfont2 libdrm
    xorg-xinit)
p9p_deps=(xorg-server libxt libxext fuse fontconfig libxft)

build-tigervnc() {
    local vnc_build_deps=(git base-devel cmake nasm xorg-font-util xorg-util-macros
        xtrans xorgproto mesa imagemagick)
    pacman -S --noconfirm --needed "${vnc_deps[@]}" "${vnc_build_deps[@]}"

    cd /
    git clone https://github.com/TigerVNC/tigervnc.git
    cd tigervnc
    git checkout $vnc_version

    cmake -G "Unix Makefiles" \
        -DCMAKE_INSTALL_PREFIX=$vnc_prefix \
        -DCMAKE_INSTALL_SBINDIR=$vnc_prefix/bin \
        -DCMAKE_INSTALL_LIBEXECDIR=$vnc_prefix/bin \
        -DBUILD_JAVA=FALSE \
        -DBUILD_VIEWER=false
    make -j$(nproc) install

    cd unix/xserver
    curl -sf "$xorg_url" | tar xfj - --strip-components=1
    patch -p1 <../xserver120.patch
    autoreconf -fiv
    CFLAGS="${CFLAGS:-} -I/usr/include/libdrm" ./configure --prefix=$vnc_prefix \
        --disable-static --without-dtrace \
        --disable-xorg --disable-xnest --disable-xvfb --disable-dmx \
        --disable-xwin --disable-xephyr --disable-kdrive --disable-xwayland \
        --disable-config-hal --disable-config-udev --with-pic \
        --disable-unit-tests --disable-devel-docs --disable-selective-werror \
        --disable-dri --enable-dri2 --enable-dri3 --enable-glx
    make -j$(nproc) install
}

build-p9p() {
    local p9p_build_deps=(git base-devel)
    pacman -S --noconfirm --needed "${p9p_deps[@]}" "${p9p_build_deps[@]}"

    cd /
    git clone https://github.com/9fans/plan9port $p9p_prefix
    cd $p9p_prefix
    git checkout $p9p_version
    export PLAN9=$p9p_prefix
    ./INSTALL
}

build-lx() {
    export PLAN9=$p9p_prefix
    PATH=$PATH:$p9p_prefix/bin
    cd /
    git clone https://github.com/perpen/lx.git
    cd /lx
    mk -f mkfile.srv install || true
}

build() {
    build-p9p
    build-lx
    build-tigervnc
}

set -x
cd "$(dirname $0)"
"$@"
