.TH LX 1
.SH NAME
lx, lxsrv \- run a command on a Linux host
.SH SYNOPSIS
.B lx
[
.B -Dd
] [
.B -c
.I dir
] [
.B -h
.I host
] [
.B -m
.I mounts
] [
.I cmd args ...
]
.PP
.B lxsrv
[
.B -i
.I address
] [
.B -p
.I port
]
.SH DESCRIPTION
.I Lx
is run from Plan 9 to execute a command
on a Linux server, with the standard file descriptors 0, 1, 2
connected to the remote process, and with the local namespace
available from Linux under mount point
.BR /mnt/term .
.PP
.B Lx
attempts to preserve the Plan 9 current directory when starting
the Linux command.
.PP
When
.IR lx
receives in a short interval 1 (resp. 2, 3) interrupt notes, it
sends signal INT (resp. HUP, KILL) to the remote process group.
.PP
If a command is not specified, a default command
from the configuration file will be run.
.PP
The options to
.IR lx
are:
.TP
.B  -d
Enable debug mode. Some extra information is printed
to stderr, originating from both client and server.
.TP
.B  -h
Connect to the specified Linux host, which must be mentioned
in the file described in lx(6).
.TP
.B  -c
Change to the specified directory before running the command.
By default the Linux server will try changing the working
directory to the Plan 9 one, but a chdir
failure will not prevent the command execution unless option
.B -D
is used.
.TP
.B  -m
The parameter specifies the bind-mounts that should be performed
before running the process. The syntax for this parameter is
described under option
.IR mounts
in lx(6).
.PP
.IR Lxsrv
runs on the Linux host, and supports the following options:
.TP
.B  -i
IP address to listen on, default is localhost.
.TP
.B  -p
Port to listen on, default is 9000.
.SH EXAMPLES
.ft L
.nf
% lx
% lx firefox
% ls -l | lx gawk '{print $4}'
% lx go build
% lx python -i
.fi
.SH FILES
$home/lib/lx \- Configuration file
.SH SEE ALSO
lx(6)
.PP
See the README for https://github.com/perpen/lx
.SH DIAGNOSTICS, BUGS
See the README for https://github.com/perpen/lx
